Aqcu 818
USGS-R/repgen pull request #405
Opened 2016-09-16 16:31 UTC by kmschoep-usgs

lines 267-270, should I also genericize the max_DV, mean_DV, etc. variables? Feels sloppy not to, but not sure of downstream implications and how much that would expand scope.

2016-09-16 16:38 UTC, lindsaycarr commented
@kmschoep-usgs use CTRL+SHIFT+F to search all scripts for where those occur - might only be one other place

2016-09-19 14:35 UTC, lindsaycarr commented on R/uvhydrograph-data.R
> -                                            subsetByMonth=TRUE, month=month, point_type=26, approvalsAtBottom=FALSE)
huh, I wonder how 26 did not cause a problem before - it's not actually a supported point type at this time

2016-09-19 14:36 UTC, lindsaycarr commented on R/uvhydrograph-data.R
> +    approvals_third_stat <- getApprovals(data, chain_nm="thirdDownChain", legend_nm=data[['reportMetadata']][["downChainDescriptions3"]],
We should probably have the code ordered correctly: first, second, third, fourth. Seems weird to be out of order

2016-09-19 14:37 UTC, lindsaycarr commented on R/uvhydrograph-data.R
> +    approvals_third_stat <- getApprovals(data, chain_nm="thirdDownChain", legend_nm=data[['reportMetadata']][["downChainDescriptions3"]],
and have that carried out through the rest of this section

2016-09-19 14:38 UTC, kmschoep-usgs commented on R/uvhydrograph-data.R
> -                                            subsetByMonth=TRUE, month=month, point_type=26, approvalsAtBottom=FALSE)
I checked on QA and those points don't render.

2016-09-19 14:38 UTC, kmschoep-usgs commented on R/uvhydrograph-data.R
> +    approvals_third_stat <- getApprovals(data, chain_nm="thirdDownChain", legend_nm=data[['reportMetadata']][["downChainDescriptions3"]],
I can do that.

2016-09-19 14:40 UTC, lindsaycarr commented on R/uvhydrograph-data.R
> +                       stat_3 = "thirdDownChain")
testing the review feature

2016-09-19 14:41 UTC, lindsayplatt requested changes
change the order and then we are good to merge!

2016-09-19 14:42 UTC, lindsaycarr commented on R/uvhydrograph-data.R
> -                                            subsetByMonth=TRUE, month=month, point_type=26, approvalsAtBottom=FALSE)
ah, so we just did not notice before

2016-09-19 14:58 UTC, lindsayplatt approved these changes

2016-09-19 15:31 UTC, merged

2016-09-19 16:23 UTC, thongsav-usgs commented
Only thing I'd suggest is updating all the test data (I'd be fine doing a text search/replace rather than regenerating all of the data). As of now, the build passes because the those fields are optional and we aren't actually rendering them anymore in the tests.