AQCU-843: Made appearance of * and ** in report header dynamic based …
USGS-R/repgen pull request #426
Opened 2016-10-03 21:33 UTC by zmoore-usgs

…on if it is included in the report or not.

2016-10-03 21:34 UTC, zmoore-usgs commented on R/sitevisitpeak-data.R
> +}
I'm really not sure if this is the most efficient way of figuring out if any of the values are outside of the specified range before actually rendering the table, so I'm certainly open to suggestions and feedback here.

2016-10-03 21:41 UTC, zmoore-usgs commented on R/sitevisitpeak-data.R
> +}
Code that is nearly identical to this already exists in one of the main rendering functions for this plot (formatSVPData) but I couldn't come up with a cleaner way of reusing it than this, so any suggestions on that would be welcome as well.

2016-10-04 13:45 UTC, lindsayplatt requested changes
put some ideas about how to change this, but the larger suggested change using apply + function rather than a loop is probably out of scope.

2016-10-04 13:45 UTC, lindsayplatt commented on R/sitevisitpeak-data.R
> +  data <- data$readings
probably name this `readings_data` or something to not just overwrite data -- or pass in `data$readings` to begin with

2016-10-04 13:45 UTC, lindsayplatt commented on R/sitevisitpeak-data.R
> +}
rather than a for loop -- we might be able to use apply? 

Possibly following something like this, where you take the body of the for loop and make a function. 

This:

``` r
mydf <- data.frame(firstVal = c(5, 12, 8), secondVal = c(3, 9, 1.5))
toRet <- data.frame(stringsAsFactors = FALSE)
for(listRows in row.names(mydf)){
  listElements <- mydf[listRows,]

  firstVal <- listElements$firstVal
  secondVal <- listElements$secondVal
  thirdVal <- sum(firstVal, secondVal)
  toAdd <- c(firstVal, secondVal, thirdVal)
  toRet <- rbind(toRet, data.frame(t(toAdd),stringsAsFactors = FALSE))
}
```

 becomes this:

``` r
myFunc <- function(df){
    firstVal <- df['firstVal']
    secondVal <- df['secondVal']
    thirdVal <- sum(firstVal, secondVal)
    toAdd <- c(firstVal, secondVal, thirdVal)
    toAddDf <- data.frame(t(toAdd),stringsAsFactors = FALSE)
    return(toAddDf)
}
mydf <- data.frame(firstVal = c(5, 12, 8), secondVal = c(3, 9, 1.5))
toRet_list <- apply(mydf, 1, myFunc)
toRet <- do.call(rbind, toRet_list)
```

2016-10-04 13:45 UTC, lindsaycarr commented on R/sitevisitpeak-data.R
> +    diff <- append(diff, getIvDifference(listElements$value, listElements$associatedIvValue))
don't use `diff` as a variable name - it's an existing function

2016-10-04 15:05 UTC, lindsayplatt approved these changes

2016-10-04 15:05 UTC, merged