Corrected approval bar positioning for linear case in ApprovalBarY()
USGS-R/repgen pull request #475
Opened 2016-12-05 17:26 UTC by ashalper-usgs

2016-12-07 20:46 UTC, lindsayplatt requested changes

2016-12-07 20:46 UTC, lindsaycarr commented on R/utils-shared.R
> -      y <- e.1 + ratio * (e.1 - e.0)
The change you made corrects the issue for linear, but I think there would also be an issue with logged here. So, I believe we would want to change everything to:

```r
if (ylog) {
  buff <- ratio * (log10(e.1) - log10(e.0))
  y <- 10^(log10(e.0) - buff)
} else {
  buff <- ratio*(e.1 - e.0)
  y <- e.0 - buff
}
```

2016-12-08 18:30 UTC, ashalper-usgs commented on R/utils-shared.R
> -      y <- e.1 + ratio * (e.1 - e.0)
OK, done.

2016-12-08 20:42 UTC, lindsayplatt approved these changes

2016-12-08 23:34 UTC, merged