AQCU-1052 first pass fix for extremes report
USGS-R/repgen pull request #627
Opened 2017-04-10 14:53 UTC by mhines-usgs

error seen, when primary and related upchain number of values mismatch an internal error occurred
now, it merges the two datasets into one dataframe and assigns NAs to values missing in one or the other.

2017-04-10 15:17 UTC, dpattermann-usgs commented on R/extremes-data.R
> +              nrow(x$points) > nrow(x$relatedPrimary)) {
Could these two if statements be simplified to nrow(x$related{Primary or Upchain}) != nrow(x$points) ?

2017-04-10 15:19 UTC, mhines-usgs commented on R/extremes-data.R
> +              nrow(x$points) > nrow(x$relatedPrimary)) {
is that a thing?! i'm actually writing a whole separate function now to reduce the duplicity of these two sets of statements as well and will try that..

2017-04-10 15:22 UTC, dpattermann-usgs commented on R/extremes-data.R
> +              nrow(x$points) > nrow(x$relatedPrimary)) {
Ha, I just mean replace each of those statements, it won't just be one statement.

2017-04-10 15:24 UTC, dpattermann-usgs commented on R/extremes-data.R
> +              nrow(x$points) > nrow(x$relatedPrimary)) {
Like (if(nrow(x$relatedPrimary) != nrow(x$points){ blah }
       if(nrow(x$relatedUpchain) != nrow(x$points))
Sorry for the confusion, I don't have any secret R magic to get rid of the duplication off the top of my head.

2017-04-12 14:58 UTC, zmoore-usgs requested changes
The approach looks good to me, though I'd suggest instead of giving each row the footnote string perhaps "footnote" should just hold TRUE or FALSE and then instead of including the if/else in the for loop in extremesTable I think you could just do return(list(toRet=toRet, footnote=any(dataRows$footnote))

Then in the RMD file add the actual footnote text if footnote=true, similar to how the other notes are being added about the '*' characters

2017-04-12 16:12 UTC, mhines-usgs commented
thanks @zmoore-usgs now that I got all the tests working again, I'll give that a try.

2017-04-14 16:55 UTC, closed without merging

2017-04-14 16:56 UTC, zmoore-usgs commented
I took this ticket from @mhines-usgs after she left and made a few tweaks. New PR: https://github.com/USGS-R/repgen/pull/637