AQCU-1125: adding legend to derivation chain report including the pro…
USGS-R/repgen pull request #693
Opened 2017-06-13 18:38 UTC by mhines-usgs

…cessor types

2017-06-13 21:40 UTC, thongsav-usgs requested changes

2017-06-13 21:40 UTC, thongsav-usgs commented on R/utils-render.R
> +  #load symbology processor images for derivation chain report
This should not be in the shared global function. There is a place for it in derivationchain-data.R.

2017-06-13 21:40 UTC, thongsav-usgs commented on R/utils-render.R
> +loadLegendSymbologyDerivationChain <- function() {
I'd also move this function to derivationchain-data.R

2017-06-13 21:40 UTC, thongsav-usgs commented on inst/templates/derivationchain/body.mustache
> +<img src="data:image/jpeg;base64,{{derivationChainSymbols.ratingModelDerived}}" title="Rating derived" alt="Rating derived"> Rating derived<br/>
Once you move the functions to derivationchain-data.R, you should be able to access the same information with reportData.derivationChainSymbols.ratingModelDerived

2017-06-14 15:53 UTC, mhines-usgs commented on R/utils-render.R
> +loadLegendSymbologyDerivationChain <- function() {
:+1:

2017-06-14 15:54 UTC, mhines-usgs commented on R/utils-render.R
> +  #load symbology processor images for derivation chain report
duh, woops. :+1:

2017-06-14 15:54 UTC, mhines-usgs commented on inst/templates/derivationchain/body.mustache
> +<img src="data:image/jpeg;base64,{{derivationChainSymbols.ratingModelDerived}}" title="Rating derived" alt="Rating derived"> Rating derived<br/>
hah, i missed this but you're correct :) :+1:

2017-06-14 17:01 UTC, thongsav-usgs approved these changes

2017-06-14 17:01 UTC, merged